version: "2"
services:

    web:
        build:
          context: ./client
          dockerfile: Dockerfile.dev
        volumes:
          - "./client:/src"
          - /src/node_modules
        working_dir: /src
        command: 'npm run dev'
        ports:
          - 6800:1998
    
    clojure:
        build: ./clojure

    nginx:
        # image: nginx
        build: ./proxy
        ports:
            - "3100:3100"
        links:
            - web
            - clojure
